name: C++ DevOps Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y build-essential make
      - name: Compile tests
        run: make compile_test

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run tests
        run: make run_test

  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install clang-tidy
        run: sudo apt-get update && sudo apt-get install -y clang-tidy
      - name: Lint source files
        run: |
          clang-tidy bst.cpp -- -std=c++11 -I.
          clang-tidy test_bst.cpp -- -std=c++11 -I.

  package:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install packaging tools
        run: sudo apt-get update && sudo apt-get install -y make dpkg-dev
      - name: Build Debian package
        run: make build-deb
      - name: Upload .deb package
        uses: actions/upload-artifact@v4
        with:
          name: bst-project.deb
          path: bst-project_1.0.deb
